{
 "title": "Scaphandre example dashboard Copy",
 "time": { "from": "2023-07-07T13:21:07.000Z", "to": "now" },
 "templating": {
  "list": [
   { "name": "PROMETHEUS_DS", "query": "prometheus" },
   { "name": "process_filter" }
  ]
 },
 "panels": [
  {
   "title": "Neural Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true
  },
  {
   "title": "Neural Net CPU Power",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "expr": "sum(scaph_process_power_consumption_microwatts{cmdline=~\".*train\\\\.py.*\"}/1000000)",
     "legendFormat": "Network CPU Power"
    }
   ]
  },
  {
   "title": "GPU Power",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    { "expr": "gpu_usage", "legendFormat": "GPU Power draw" }
   ]
  },
  {
   "title": "Neural Net GPU Memory usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    { "expr": "network_gpu_memory_usage_mb", "legendFormat": "Network GPU memory usage" }
   ]
  },
  {
   "title": "GPU+CPU Power",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "sum(scaph_process_power_consumption_microwatts{cmdline=~\".*train\\\\.py.*\"}/1000000)"
    },
    { "expr": "gpu_usage" }
   ]
  },
  {
   "title": "Power usage",
   "type": "stat",
   "description": "Average Neural Network Power",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(scaph_process_power_consumption_microwatts{cmdline=~\".*train\\\\.py.*\"}/1000000)*0.00417",
     "legendFormat": "CPU Net Power used"
    },
    { "expr": "gpu_usage*0.00417", "legendFormat": "GPU Power used" }
   ]
  },
  {
   "title": "Memory usage",
   "type": "stat",
   "gridPos": { "h": 7, "w": 10, "x": 8, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "network_gpu_memory_usage_mb", "legendFormat": "GPU Memory usage" }
   ]
  },
  {
   "title": "Per hosts",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Hosts power consumption",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "W" }
   ],
   "targets": [
    {
     "expr": "scaph_host_power_microwatts / 1000000",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Hosts power consumption total (dynamic time range)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "Wh" }
   ],
   "targets": [
    {
     "expr": "sum(avg_over_time(scaph_host_power_microwatts[1h]))/1000000",
     "legendFormat": "total of hosts, during displayed time window"
    }
   ]
  },
  {
   "title": "Per CPU Sockets",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Socket power consumption",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "W" }
   ],
   "targets": [
    {
     "expr": "scaph_socket_power_microwatts / 1000000",
     "legendFormat": "{{instance}} Socket {{socket_id}}"
    }
   ]
  },
  {
   "title": "Per process",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Top process consumers",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sort_desc(topk(3, sum by (exe) (scaph_process_power_consumption_microwatts/1000000)))",
     "legendFormat": "{{exe}}"
    }
   ]
  },
  {
   "title": "Filtered process (process_filter) power, by exe",
   "type": "graph",
   "gridPos": { "h": 7, "w": 16, "x": 8, "y": 41 },
   "yaxes": [
    { "format": "W" }
   ],
   "targets": [
    {
     "expr": "scaph_process_power_consumption_microwatts{exe=~\".*${process_filter}.*\"}/1000000",
     "legendFormat": "{{ cmdline }}"
    }
   ]
  }
 ]
}